### ISSUE TITLE
New update broke it.

### ISSUE THREAD

**Issue by Idiafh** [nedhyett/Vermilion#174]
http://steamcommunity.com/workshop/filedetails/discussion/338063408/523897277911238783/

**Comment by nedhyett** [comment]
Looks pretty serious... I'm low on time. I'll try to get a fix for it as soon as I can, but my schedule is pretty full right now.

Note to self: install new GPU for development machine and find the lost version.

**Comment by nedhyett** [comment]
I haven't signed into steam recently due to piles of homework keeping me away from it, so I didn't get the messages. My account is going to have so many notifications when I log in tomorrow. (I can't promise anything being released tomorrow, however).

I can't comment on steam because I'm on my iPad which is not authenticated for steam and left my phone at college, so I can't two-factor login.

**Comment by nedhyett** [comment]
While I'm at it, are there any errors in the console? How about complaints from Vermilion's GUI toolkit?

**Comment by Revo78** [comment]
[Vermilion2 - Client] An error has been detected in the base GMod hook system. This most likely has nothing to do with Vermilion.
lua/vermilion2/geoip.lua:195: bad argument #1 to 'lower' (string expected, got nil)

Trace: 
	1: Line 32	"Trace"	lua/includes/extensions/debug.lua
	2: Line 136	"nil"	lua/vermilion2/core/hooks.lua
3	C function
	4: Line 195	"hookFunc"	lua/vermilion2/geoip.lua
	5: Line 113	"Run"	lua/vermilion2/core/hooks.lua
	6: Line 82	"hookFunc"	lua/vermilion2/targetid.lua
	7: Line 113	"Run"	lua/vermilion2/core/hooks.lua
	8: Line 75	"HUDPaint"	gamemodes/base/gamemode/cl_init.lua
	9: Line 75	"oldHook"	gamemodes/sandbox/gamemode/cl_init.lua
	10: Line 131	"nil"	lua/vermilion2/core/hooks.lua
11	C function
	12: Line 130	"nil"	lua/vermilion2/core/hooks.lua

I'm getting this since last Gmod update.

**Comment by nedhyett** [comment]
That can't possibly be it... How is the GeoIP breaking anything... and how did I forget to move the GeoIP out of the vanilla hook system? Something really strange must be going on here...
