### ISSUE TITLE
'!cleanup' command not working

### ISSUE THREAD

**Issue by frdyttedf1** [nedhyett/Vermilion#188]
'!cleanup [playername]' not doing anything. I see this error a ton of times in the console, 

> CClientSteamContext OnSteamServerConnectFailure logged on = 0
CClientSteamContext OnSteamServerConnectFailure logged on = 0
CClientSteamContext OnSteamServerConnectFailure logged on = 0

But I'm not sure if that is related. When I enter the command it doesn't produce any output (other then those messages, if they are related). 

In case this helps, here's the servers set of addons; http://steamcommunity.com/sharedfiles/filedetails/?id=509678282

**Comment by nedhyett** [comment]
Looks like you aren't connected to Steam. Vermilion uses player SteamIDs to validate ownership of props and track user activity on the server. If you aren't connected to Steam, the translation between SteamID and username can fail and will produce output like this. As far as I remember, Garry's Mod will also produce this when Steam is running in Offline Mode, since it can't track achievements then and it counts every second the game is played to increase the time stats. Have you checked to see if this is the case?

**Comment by frdyttedf1** [comment]
It appears that my server is using an anonymous steam server ID to validate with steam. I shall try to correct this right now.

**Comment by frdyttedf1** [comment]
Ah, I see the issue. In order for a steam auth key to be valid, you must have the steam guard mobile authenticator set up.

**Comment by nedhyett** [comment]
That shouldn't be a problem. That's what I use too. Those errors relate to Steam connections, but the anonymous account shouldn't matter. I'll have to do extra investigation.
