### ISSUE TITLE
Switchable Seats Incompatibility

### ISSUE THREAD

**Issue by TwistedTail** [nedhyett/Vermilion#82]
Just a reminder of this:

File exists in two addons - possible conflicts! lua/autorun/switchableseats.lua (Switchable seats and Vermilion 2)

[ERROR] lua/vermilion2/modules/event_logger/init.lua:139: attempt to index a nil value
1. hookFunc - lua/vermilion2/modules/event_logger/init.lua:139
2. unknown - lua/vermilion2/shared.lua:210
3. EnterVehicle - [C]:-1
4. v - lua/autorun/switchableseats.lua:407
5. oldHook - lua/includes/modules/hook.lua:84
6. unknown - lua/vermilion2/shared.lua:219

Also, it just happens in Singleplayer

**Comment by nedhyett** [comment]
Will be fixed in next commit, I hope. I tried it out and it didn't seem to error after I added extra checks to the event logger hook. Although, the next commit itself will most likely be unusable anyway as I'm staging a rewrite at the moment. I'll close the issue if it is resolved when the final 2.5 release is ready.

**Comment by nedhyett** [comment]
Just tested it myself and it appears to be resolved. I can't be sure though. I'll reopen the issue if it becomes a problem again.
